import { createHash } from "node:crypto";
import { normalizeExtraction } from "./normalize";
import { INVOICE_PROMPT_VERSION } from "./prompts/invoice";
import { EXTRACTION_SCHEMA_VERSION } from "./schema";
import type { DocumentExtractionProvider, ExtractionInput, ExtractionResult } from "./types";

/**
 * Deterministic, offline provider for development and automated tests.
 * Returns clearly SYNTHETIC data (supplier "Fornecedor Exemplo") derived from a
 * hash of the file, so the same file always yields the same extraction.
 * It never inspects document content and must not be used in production.
 *
 * Special behaviour for tests: files whose bytes contain the marker
 * "MOCK_AI_FAIL" produce a provider failure, and "MOCK_AI_INVALID" produce an
 * invalid (schema-violating) response.
 */
export class MockExtractionProvider implements DocumentExtractionProvider {
  readonly name = "mock";
  readonly model = "mock-invoice-v1";

  async extractInvoice(input: ExtractionInput): Promise<ExtractionResult> {
    const started = Date.now();
    const base = {
      provider: this.name,
      model: this.model,
      promptVersion: INVOICE_PROMPT_VERSION,
      schemaVersion: EXTRACTION_SCHEMA_VERSION,
    };
    const marker = Buffer.from(
      input.bytes.subarray(0, Math.min(input.bytes.length, 200_000)),
    ).toString("latin1");
    if (marker.includes("MOCK_AI_FAIL")) {
      return {
        ok: false,
        ...base,
        errorCode: "provider_unavailable",
        errorMessage: "Simulated provider failure",
        durationMs: 1,
      };
    }
    if (marker.includes("MOCK_AI_INVALID")) {
      const raw = { document_type: "invoice", line_items: "not-an-array" };
      return {
        ok: false,
        ...base,
        errorCode: "schema_mismatch",
        errorMessage: "Simulated invalid response",
        raw,
        durationMs: 1,
      };
    }

    // Embedded synthetic metadata (used by the seed/e2e synthetic PDFs).
    const embedded = /MOCK_DATA:([A-Za-z0-9+/=]+)/.exec(marker);
    let raw: unknown;
    if (embedded?.[1]) {
      try {
        raw = JSON.parse(Buffer.from(embedded[1], "base64").toString("utf8"));
      } catch {
        raw = undefined;
      }
    }

    if (!raw) {
      const hash = createHash("sha256").update(input.bytes).digest();
      const cents = 1000 + (hash.readUInt32BE(0) % 90000); // 10.00 – 909.99
      const subtotal = (cents / 100).toFixed(2);
      const tax = ((cents * 23) / 10000).toFixed(2);
      const total = (Number(subtotal) + Number(tax)).toFixed(2);
      const n = hash.readUInt16BE(4);
      raw = {
        document_type: "invoice",
        supplier: {
          name: "Fornecedor Exemplo, Lda.",
          tax_id: "PT123456789",
          address: null,
          email: null,
        },
        customer: { name: null, tax_id: null },
        document_number: `FT MOCK/${n}`,
        issue_date: "2026-01-15",
        due_date: "2026-02-14",
        currency: "EUR",
        subtotal,
        tax_total: tax,
        total,
        tax_breakdown: [{ rate: "23", base: subtotal, amount: tax }],
        line_items: [
          {
            description: "Serviço de exemplo (dados simulados)",
            quantity: "1",
            unit_price: subtotal,
            tax_rate: "23",
            tax_amount: tax,
            line_total: subtotal,
          },
        ],
        payment_reference: null,
        iban: null,
        purchase_order: null,
        confidence: { overall: 0.5, supplier: 0.5, amounts: 0.5, dates: 0.5, document_number: 0.5 },
        warnings: ["Synthetic data generated by the mock AI provider."],
      };
    }

    const normalized = normalizeExtraction(raw);
    if (!normalized.ok) {
      return {
        ok: false,
        ...base,
        errorCode: "schema_mismatch",
        errorMessage: normalized.issues.join("; "),
        raw,
        durationMs: Date.now() - started,
      };
    }
    return { ok: true, ...base, raw, data: normalized.data, durationMs: Date.now() - started };
  }
}
